extends Node

const CARDS_IN_HAND = 5
const CARD_SIZE = 64
const CARD_SPACING = CARD_SIZE + 8
const SHORT_DELAY = 0.3
const KICKERS_WORTHLESS = true

enum HANDS {
    ROYAL_FLUSH,
    STRAIGHT_FLUSH,
    FOUR_OF_A_KIND,
    FULL_HOUSE,
    FLUSH,
    STRAIGHT,
    THREE_OF_A_KIND,
    TWO_PAIR,
    PAIR,
    HIGH_CARD,
}

const HAND_NAMES = {
    HANDS.ROYAL_FLUSH: "Royal Flush",
    HANDS.STRAIGHT_FLUSH: "Straight Flush",
    HANDS.FOUR_OF_A_KIND: "Four of a Kind",
    HANDS.FULL_HOUSE: "Full House",
    HANDS.FLUSH: "Flush",
    HANDS.STRAIGHT: "Straight",
    HANDS.THREE_OF_A_KIND: "Three of a Kind",
    HANDS.TWO_PAIR: "Two Pair",
    HANDS.PAIR: "Pair",
    HANDS.HIGH_CARD: "High Card",
}

const HAND_POINTS = {
    HANDS.ROYAL_FLUSH: 2000,
    HANDS.STRAIGHT_FLUSH: 800,
    HANDS.FOUR_OF_A_KIND: 700,
    HANDS.FULL_HOUSE: 600,
    HANDS.FLUSH: 500,
    HANDS.STRAIGHT: 400,
    HANDS.THREE_OF_A_KIND: 300,
    HANDS.TWO_PAIR: 200,
    HANDS.PAIR: 100,
    HANDS.HIGH_CARD: 0,
}
